{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "csi-driver.fullname" .}}-provisioner-binding
  labels:
    {{- include "csi-driver.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-driver.fullname" . }}-controller-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "csi-driver.fullname" . }}-provisioner
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "csi-driver.fullname" . }}-attacher-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-driver.fullname" . }}-controller-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "csi-driver.fullname" . }}-attacher
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "csi-driver.fullname" . }}-snapshotter-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-driver.fullname" . }}-controller-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "csi-driver.fullname" . }}-snapshotter
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "csi-driver.fullname" . }}-resizer-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-driver.fullname" . }}-controller-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "csi-driver.fullname" . }}-resizer
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "csi-driver.fullname" . }}-controller-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-driver.fullname" . }}-controller-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "csi-driver.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "csi-driver.fullname" . }}-node-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-driver.fullname" . }}-node-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "csi-driver.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
