apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "csi-driver.fullname" . }}-node-map
  labels:
    {{- include "csi-driver.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "csi-driver.fullname" . }}-iscsi-config
  labels:
    {{- include "csi-driver.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  iscsi: |
  {{- range $key, $val := .Values.driver.node.driver.iscsi }}
  {{- $key | nindent 4 }}: {{ $val }}
  {{- end }}
