{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "csi-driver.fullname" . }}-controller-account
  labels:
    {{- include "csi-driver.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "csi-driver.fullname" . }}-node-account
  labels:
    {{- include "csi-driver.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end }}
