apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "emqx.fullname" . }}
  labels:
    {{ include "emqx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "emqx.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{ include "emqx.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: emqx
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          env:
            - name: EMQX_NODE_NAME
              value: "{{ .Values.env.EMQX_NODE_NAME }}"
          resources:
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
          volumeMounts:
            - name: data-volume
              mountPath: {{ .Values.persistence.data.path }}
            - name: log-volume
              mountPath: {{ .Values.persistence.log.path }}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "emqx.fullname" . }}-data
        - name: log-volume
          persistentVolumeClaim:
            claimName: {{ include "emqx.fullname" . }}-log
