replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: davycloud/docker-hexo
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4000

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  hexo:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: "local"

env:
  HEXO_SERVER_PORT: "4000"
  HEXO_GIT_USER: "Your Name"
  HEXO_GIT_EMAIL: "your.email@example.com"
