apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: {{ template "openelb.admission.fullname" . }}
webhooks:
  - admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        name: {{ template "openelb.manager.fullname" . }}
        namespace: {{ template "openelb.namespace" . }}
        path: /validate-network-kubesphere-io-v1alpha2-svc
    failurePolicy: Fail
    name: mutating.eip.network.kubesphere.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - services

    sideEffects: NoneOnDryRun