replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: bloodstar/hexo
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4000

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi  # Persistent volume size
  storageClass: "local"  # 动态存储类

env:
  - name: NODE_ENV
    value: production
  - name: HEXO_DEBUG
    value: "false"
  - name: CUSTOM_VAR
    valueFrom:
      secretKeyRef:
        name: my-secret
        key: customKey
