replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: linuxserver/code-server
  tag: "4.93.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8443
  externalPort: 80

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

persistence:
  enabled: true
  path: /config
  size: 5Gi

env:
  PUID: "1000"
  PGID: "1000"
  TZ: "Asia/Shanghai"
  PASSWORD: "yunna"
  SUDO_PASSWORD: "yunna"
  DEFAULT_WORKSPACE: "/config/workspace"
