replicaCount: 1

image:
  repository: registry-2.yunna.net/itzg/minecraft-server
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 25565
  nodePort: 32025

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 1

minecraftServer:
  eula: "TRUE"
  type: "PAPER"
  memory: "1G"