{{- if .Values.podSecurityPolicies.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "elasticsearch-exporter.fullname" . }}
  labels:
    {{- include "elasticsearch-exporter.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "elasticsearch-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  {{- if .Values.serviceAccount.create  }}
  name: {{ template "elasticsearch-exporter.fullname" . }}
  {{- else }}
  name: {{ .Values.serviceAccount.name }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
{{- end }}
