{{- if .Values.podSecurityPolicies.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "elasticsearch-exporter.fullname" . }}
  labels:
    {{- include "elasticsearch-exporter.labels" . | indent 4 }}
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "elasticsearch-exporter.fullname" . }}
{{- end }}
