{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "elasticsearch-exporter.fullname" . }}
  labels:
    {{- include "elasticsearch-exporter.labels" . | indent 4 }}
{{- end }}
