replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: mysql
  tag: "5.6"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: "local"

mysql:
  rootPassword: "mysql123456"

env:
  env1:
    name: TZ
    value: Asia/Shanghai
  env2:
    name: MYSQL_DATABASE
    value: test

initContainerResources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"
