image:
  repository: mysql
  tag: "8.0"

mysqlRootPassword: "rootpassword"

service:
  type: ClusterIP
  port: 3306

persistence:
  enabled: true
  size: 8Gi
  storageClass: "local"
  pvcName: ""  # 留空时动态生成 PVC 名称
