replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

mysql:
  rootPassword: changeme
  database: mydb
  user: user
  password: changeme

service:
  type: ClusterIP
  port: 3306

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: "local"

env:
  env1:
    name: MYSQL_ROOT_PASSWORD
    value: "{{ .Values.mysql.rootPassword }}"
  env2:
    name: MYSQL_DATABASE
    value: "{{ .Values.mysql.database }}"
  env3:
    name: MYSQL_USER
    value: "{{ .Values.mysql.user }}"
  env4:
    name: MYSQL_PASSWORD
    value: "{{ .Values.mysql.password }}"