replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: organization/template-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: "local"

env:
  - name: APP_ENV
    value: production
  - name: DEBUG
    value: "false"
