apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-discourse-pvc
  labels:
    app.kubernetes.io/name: {{ include "discourse.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.discourse.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.discourse.size }}
  storageClassName: {{ .Values.persistence.discourse.storageClass }}
