apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "discourse.fullname" . }}-discourse-pvc
  labels:
    {{ include "discourse.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.discourse.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.discourse.size }}
  storageClassName: {{ .Values.persistence.discourse.storageClass }}
