apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "discourse.fullname" . }}-postgresql-pvc
  labels:
    {{ include "discourse.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.postgresql.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.postgresql.size }}
  storageClassName: {{ .Values.persistence.postgresql.storageClass }}
