apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgresql-pvc
  labels:
    app: {{ .Release.Name }}-postgresql
spec:
  accessModes:
    - {{ .Values.persistence.postgresql.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.postgresql.size }}
  storageClassName: {{ .Values.persistence.postgresql.storageClass }}
