apiVersion: v1
kind: Service
metadata:
  name: {{ include "discourse.fullname" . }}-postgresql
  labels:
    {{ include "discourse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
  selector:
    app: {{ include "discourse.fullname" . }}-postgresql
