apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  {{- include "openelb.admission.labels" . | nindent 4 }}
  name: {{ template "openelb.admission.fullname" . }}
  namespace: {{ template "openelb.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "openelb.admission.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "openelb.admission.serviceAccountName" . }}
    namespace: {{ template "openelb.namespace" . }}