{{- if or .Values.admission.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "openelb.admission.serviceAccountName" . }}
  namespace: {{ template "openelb.namespace" . }}
  labels:
  {{- include "openelb.admission.labels" . | nindent 4 }}
{{- end }}
