{{ if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: iomesh
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
  - '*'
allowedUnsafeSysctls:
  - '*'
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{ .Release.Namespace }}:csi-driver-controller-account
- system:serviceaccount:{{ .Release.Namespace }}:csi-driver-node-account
- system:serviceaccount:{{ .Release.Namespace }}:builder
- system:serviceaccount:{{ .Release.Namespace }}:default
- system:serviceaccount:{{ .Release.Namespace }}:deployer
- system:serviceaccount:{{ .Release.Namespace }}:openebs-ndm-operator
- system:serviceaccount:{{ .Release.Namespace }}:operator
- system:serviceaccount:{{ .Release.Namespace }}:operator-hostpath-provisioner
- system:serviceaccount:{{ .Release.Namespace }}:operator-zookeeper-operator-post-install-upgrade
- system:serviceaccount:{{ .Release.Namespace }}:operator-zookeeper-operator-post-install-upgrade
- system:serviceaccount:{{ .Release.Namespace }}:zookeeper-operator
{{ end }}
