{{ if .Values.controller.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crane-scheduler-controller
  labels:
    {{- include "crane.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - list
  - watch
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crane-scheduler-controller
  labels:
    {{- include "crane.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crane-scheduler-controller
subjects:
- kind: ServiceAccount
  name: crane-scheduler-controller
  namespace: {{ .Release.Namespace }}
{{ end }}