{{ if .Values.controller.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crane-scheduler-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crane.labels" . | nindent 4 }}
{{ end }}