{{ if .Values.scheduler.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crane.labels" . | nindent 4 }}
{{ end }}