apiVersion: v1
kind: Service
metadata:
  name: storageclass-accessor
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: storageclass-accessor
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
