apiVersion: v1
kind: Service
metadata:
  name: { { include "onlyoffice-documentserver.fullname" . } }
  labels: { { - include "onlyoffice-documentserver.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 80
  selector:
    { { - include "onlyoffice-documentserver.selectorLabels" . | nindent 4 } }
