replicaCount: 1

image:
  repository: phusion/baseimage
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 22
  name: ssh

readinessProbe:
  exec:
    command:
      - cat
      - /etc/service/sshd/down
  initialDelaySeconds: 5
  periodSeconds: 3
  failureThreshold: 6

livenessProbe:
  exec:
    command:
      - cat
      - /etc/service/sshd/down
  initialDelaySeconds: 5
  periodSeconds: 3

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
