{{- if .Values.iomesh.create -}}
{{- if or .Values.iomesh.serviceMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "iomesh.name" . }}
  namespace: {{ default .Release.Namespace .Values.iomesh.serviceMonitor.namespace }}
  {{- if .Values.iomesh.serviceMonitor.labels }}
  labels:
    {{- toYaml .Values.iomesh.serviceMonitor.labels | nindent 4 }}
  {{- end }}
spec:
  jobLabel: prometheus.io/name
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      prometheus.io/scrape: "true"
  endpoints:
  - port: meta-exporter
    path: /api/v1/prometheus/basic
    interval: 30s
    scrapeTimeout: 5s
    {{- if .Values.iomesh.meta.serviceMonitor.relabelings }}
    relabelings:
    {{- range .Values.iomesh.meta.serviceMonitor.relabelings }}
    - {{ toYaml . }}
    {{- end }}
    {{- end }}
  - port: meta-exporter
    path: /api/v1/prometheus/volume
    interval: 30s
    scrapeTimeout: 5s
    {{- if .Values.iomesh.meta.serviceMonitor.relabelings }}
    relabelings:
    {{- range .Values.iomesh.meta.serviceMonitor.relabelings }}
    - {{ toYaml . }}
    {{- end }}
    {{- end }}
  - port: chunk-exporter
    path: /api/v1/prometheus/volume
    interval: 30s
    scrapeTimeout: 5s
    {{- if .Values.iomesh.chunk.serviceMonitor.relabelings }}
    relabelings:
    {{- range .Values.iomesh.chunk.serviceMonitor.relabelings }}
    - {{ toYaml . }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- if or .Values.operator.serviceMonitor.create }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: iomesh-operator
  namespace: {{ default .Release.Namespace .Values.operator.serviceMonitor.namespace }}
  {{- if .Values.operator.serviceMonitor.labels }}
  labels:
    {{- toYaml .Values.operator.serviceMonitor.labels | nindent 4 }}
  {{- end }}
spec:
  jobLabel: prometheus.io/name
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      operator.iomesh.com/role: operator
      prometheus.io/scrape: "true"
  endpoints:
  - port: iomesh-exporter
    path: /metrics
    interval: 30s
    scrapeTimeout: 5s
    {{- if .Values.operator.serviceMonitor.relabelings }}
    relabelings:
    {{- range .Values.operator.serviceMonitor.relabelings }}
    - {{ toYaml . }}
    {{- end }}
    {{- end }}
{{- if or .Values.operator.kubeStateMetrics.create }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: {{ default .Release.Namespace .Values.operator.serviceMonitor.namespace }}
  {{- if .Values.operator.serviceMonitor.labels }}
  labels:
    {{- toYaml .Values.operator.serviceMonitor.labels | nindent 4 }}
  {{- end }}
spec:
  jobLabel: prometheus.io/name
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
      prometheus.io/scrape: "true"
  endpoints:
  - interval: 30s
    port: http-metrics
    scrapeTimeout: 5s
    {{- if .Values.operator.kubeStateMetrics.relabelings }}
    relabelings:
    {{- range .Values.operator.kubeStateMetrics.relabelings }}
    - {{ toYaml . }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
