{{- if .Values.operator.prometheusRule.create -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: {{ default .Release.Namespace .Values.operator.prometheusRule.namespace }}
  name: iomesh 
  {{- if .Values.operator.prometheusRule.labels }}
  labels:
    {{- toYaml .Values.operator.prometheusRule.labels | nindent 4 }}
  {{- end }}
spec:
  groups:
  {{- range $path, $_ := .Files.Glob "rules/*" }}
    - name: {{ $path | trimPrefix "rules/" }}
      rules:
        {{- $.Files.Get $path | nindent 8 }}
  {{- end }}
{{- end }}
