apiVersion: v1
kind: Service
metadata:
  name: {{ include "halo.fullname" . }}
  labels:
    {{ include "halo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8090
  selector:
    app.kubernetes.io/name: {{ include "halo.name" . }}
