apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "pvc-autoresizer.fullname" . }}-controller
  labels:
    {{- include "pvc-autoresizer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "pvc-autoresizer.fullname" . }}-controller
subjects:
- kind: ServiceAccount
  name: {{ template "pvc-autoresizer.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
