apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "pvc-autoresizer.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pvc-autoresizer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "pvc-autoresizer.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ template "pvc-autoresizer.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
