apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kali.fullname" . }}
  labels:
    {{- include "kali.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kali.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kali.labels" . | nindent 8 }}
        {{- include "kali.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: kali
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 22
          env:
            {{- if kindIs "array" .Values.env }}
            {{- range .Values.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}
            {{- else if kindIs "map" .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: "{{ $value.name }}"
              value: "{{ $value.value }}"
            {{- end }}
            {{- end }}
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
          volumeMounts:
            - name: kali-data
              mountPath: /root
      volumes:
        - name: kali-data
          persistentVolumeClaim:
            claimName: {{ include "kali.fullname" . }}-pvc