apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "code-server.fullname" . }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "code-server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "code-server.name" . }}
    spec:
      containers:
        - name: code-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PUID
              value: "{{ .Values.env.PUID }}"
            - name: PGID
              value: "{{ .Values.env.PGID }}"
            - name: TZ
              value: "{{ .Values.env.TZ }}"
            - name: PASSWORD
              value: "{{ .Values.env.PASSWORD }}"
            - name: HASHED_PASSWORD
              value: "{{ .Values.env.HASHED_PASSWORD }}"
            - name: SUDO_PASSWORD
              value: "{{ .Values.env.SUDO_PASSWORD }}"
            - name: SUDO_PASSWORD_HASH
              value: "{{ .Values.env.SUDO_PASSWORD_HASH }}"
            - name: PROXY_DOMAIN
              value: "{{ .Values.env.PROXY_DOMAIN }}"
            - name: DEFAULT_WORKSPACE
              value: "{{ .Values.env.DEFAULT_WORKSPACE }}"
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.persistence.path }}
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: code-server-pvc
