apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "code-server.fullname" . }}
  labels:
    {{ include "code-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "code-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{ include "code-server.labels" . | nindent 8 }}
    spec:
      containers:
        - name: code-server
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PUID
              value: "{{ .Values.env.PUID }}"
            - name: PGID
              value: "{{ .Values.env.PGID }}"
            - name: TZ
              value: "{{ .Values.env.TZ }}"
            - name: PASSWORD
              value: "{{ .Values.env.PASSWORD }}"
            - name: SUDO_PASSWORD
              value: "{{ .Values.env.SUDO_PASSWORD }}"
            - name: DEFAULT_WORKSPACE
              value: "{{ .Values.env.DEFAULT_WORKSPACE }}"
          resources:
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.persistence.path }}
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: {{ include "code-server.fullname" . }}-config
