apiVersion: v1
kind: Service
metadata:
  name: {{ include "code-server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
  selector:
    app: {{ include "code-server.name" . }}
