apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filebrowser.fullname" . }}
  labels:
    {{ include "filebrowser.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "filebrowser.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{ include "filebrowser.labels" . | nindent 8 }}
    spec:
      containers:
        - name: filebrowser
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: srv-volume
              mountPath: /srv
            - name: config-volume
              mountPath: /var/config
          resources:
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
      volumes:
        - name: srv-volume
          persistentVolumeClaim:
            claimName: {{ include "filebrowser.fullname" . }}-srv
        - name: config-volume
          persistentVolumeClaim:
            claimName: {{ include "filebrowser.fullname" . }}-config
