replicaCount: 1

image:
  repository: http://registry.yunna.net/ubuntu
  tag: "22.04"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: ["/"]

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
