replicaCount: 1

image:
  repository: http://registry.yunna.net/ubuntu
  tag: "20.04"
  pullPolicy: IfNotPresent
  availableTags:
    - "18.04"
    - "20.04"
    - "22.04"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: ["/"]

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
