# 副本数量
replicaCount: 1

# 镜像配置
image:
  imageRegistry: "registry-2.yunna.net" # 镜像加速站
  repository: onlyoffice/documentserver # 镜像名称
  tag: "latest" # 镜像标签
  pullPolicy: IfNotPresent # 拉取策略

# 服务配置
service:
  type: ClusterIP # 服务类型（ClusterIP, NodePort, LoadBalancer）
  port: 80 # 服务端口

# 持久化存储配置
persistence:
  enabled: true # 是否启用持久化
  accessMode: ReadWriteOnce # 持久化存储访问模式
  size: 10Gi # 存储大小
  storageClass: "local" # 存储类名称

# 环境变量
env:
  env1:
    name: NODE_ENV
    value: "production"
  env2:
    name: SECRET_KEY
    value: "super-secure-key"
  env3:
    name: JWT_ENABLED
    value: "false"
  env4:
    name: ENABLE_HTTPS
    value: "false"
  env5:
    name: DOCUMENTSERVER_PORT
    value: "80"
