# 副本数量
replicaCount: 1

# 镜像配置
image:
  imageRegistry: "docker.io" # Docker Hub 注册表
  repository: onlyoffice/documentserver # 镜像名称
  tag: "latest" # 镜像标签
  pullPolicy: IfNotPresent # 拉取策略

# 服务配置
service:
  type: ClusterIP # 服务类型（ClusterIP, NodePort, LoadBalancer）
  port: 80 # 服务端口

# 持久化存储配置
persistence:
  enabled: true # 是否启用持久化
  accessMode: ReadWriteOnce # 持久化存储访问模式
  size: 10Gi # 存储大小
  storageClass: "local" # 存储类名称

# 环境变量
env:
  NODE_ENV:
    name: NODE_ENV
    value: "production" # 默认运行环境为 production
  SECRET_KEY:
    name: SECRET_KEY
    value: "请设置你的密码" # 必须设置的安全密钥
  JWT_ENABLED:
    name: JWT_ENABLED
    value: "false" # 默认关闭 JWT
  ENABLE_HTTPS:
    name: ENABLE_HTTPS
    value: "false" # 默认关闭 HTTPS
  DOCUMENTSERVER_PORT:
    name: DOCUMENTSERVER_PORT
    value: "80" # 默认端口为 80
