replicaCount: 1

image:
  imageRegistry: ""
  repository: halohub/halo
  tag: "2.20"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8090

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: ""

env: []
