{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hostpath-provisioner.serviceAccountName" . }}
  labels:
    {{- include "hostpath-provisioner.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    helm.sh/resource-policy: keep
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
