apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "openelb.manager.fullname" . }}
  namespace: {{ template "openelb.namespace" . }}
  labels:
    {{- include "openelb.manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "openelb.manager.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "openelb.manager.serviceAccountName" . }}
  namespace: {{ template "openelb.namespace" . }}
