apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hexo.fullname" . }}-pvc  # 使用模板函数生成名称
  labels:
    {{ include "hexo.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.hexo.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.hexo.size }}
  storageClassName: {{ .Values.persistence.hexo.storageClass | quote }}
