containers:
  - name: uptime-kuma
    image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: "{{ .Values.image.pullPolicy }}"
    ports:
      - containerPort: 3001
    env:
      {{- range .Values.env }}
      - name: "{{ .name }}"
        value: "{{ .value }}"
      {{- end }}
    resources:
      requests:
        memory: "{{ .Values.resources.requests.memory }}"
        cpu: "{{ .Values.resources.requests.cpu }}"
      limits:
        memory: "{{ .Values.resources.limits.memory }}"
        cpu: "{{ .Values.resources.limits.cpu }}"
    volumeMounts:
      - name: uptime-kuma-data
        mountPath: /app/data
volumes:
  - name: uptime-kuma-data
    persistentVolumeClaim:
      claimName: {{ include "uptime-kuma.fullname" . }}-pvc
