apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "uptime-kuma.fullname" . }}-pvc
  labels:
    app: {{ include "uptime-kuma.name" . }}
spec:
  accessModes:
    - {{ .Values.persistence.uptimeKuma.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.uptimeKuma.size }}
  storageClassName: {{ .Values.persistence.uptimeKuma.storageClass | quote }}
