apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptime-kuma.fullname" . }}
  labels:
    app: {{ include "uptime-kuma.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3001
  selector:
    app: {{ include "uptime-kuma.name" . }}
