kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ include "localpvManager.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "localpvManager.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "localpvManager.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "localpvManager.name" .}}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: {{ .Values.localpvManager.hostNetwork }}
      containers:
        - name: localpv-manager
          image: {{ include "localpvManager.image" . }}
          imagePullPolicy: {{ .Values.localpvManager.image.pullPolicy }}
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          ports:
            - containerPort: {{ .Values.localpvManager.ports.health }}
              name: health
              protocol: TCP
            - containerPort: {{ .Values.localpvManager.ports.liveness }}
              name: liveness
              protocol: TCP
          resources: {{ toYaml .Values.localpvManager.resources | nindent 12 }}
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 2
            httpGet:
              path: /healthz
              port: health
          command:
          - /localpv-manager
          args:
            - --csi_addr=unix:///csi/csi.sock
            - --driver_name={{ include "localpvManager.csi.name" .}}
            - --v=1
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- include "localpvManager.volumeMounts" . | nindent 10 -}}
        {{- include "localpvManager.sidecar" . | indent 8 }}
      {{- with .Values.localpvManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.localpvManager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.localpvManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "localpvManager.volumes" . | nindent 6 -}}
