{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "localpvManager.name" . }}
  labels:
    {{- include "localpvManager.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end }}
