apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-{{ include "cloudreve.fullname" . }}-data
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
  storageClassName: "local"  # 明确指定使用 local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloudreve.fullname" . }}-data
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloudreve.fullname" . }}-config
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.persistence.storageClass }}