apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudreve
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cloudreve
  template:
    metadata:
      labels:
        app: cloudreve
    spec:
      containers:
        - name: cloudreve
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5212
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "{{ .Values.mysql.username }}"
            - name: DB_PASSWORD
              value: "{{ .Values.mysql.password }}"
            - name: DB_NAME
              value: "{{ .Values.mysql.database }}"
          volumeMounts:
            - name: uploads
              mountPath: /cloudreve/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: cloudreve-pvc
