apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudreve-ingress
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloudreve
                port:
                  number: {{ .Values.service.port }}
