apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | join "," }}
  resources:
    requests:
      storage: {{ .Values.mysql.storageSize }}
  storageClassName: {{ .Values.persistence.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudreve-pvc
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | join "," }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}
