apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudreve.fullname" . }}
  labels:
    {{- include "cloudreve.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5212
      protocol: TCP
      name: http
  selector:
    {{- include "cloudreve.selectorLabels" . | nindent 4 }}
