apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-blockdevice-monitor-prober
  namespace: {{ .Release.Namespace }}
  labels:
    app: blockdevice-monitor-prober
spec:
  selector:
    matchLabels:
      app: blockdevice-monitor-prober
  template:
    metadata:
      labels:
        app: blockdevice-monitor-prober
    spec:
      containers:
      - name: prober
        command:
        - /opt/blockdevice-monitor/bin/prober
        - --enable-prober-iostat={{ .Values.prober.iostat.enable }}
        - --iostat-loop-interval-sec={{ .Values.prober.iostat.loopIntervalSec }}
        - --sampling-win-size={{ .Values.prober.iostat.samplingWinSize }}
        - --threshold-ssd-latency-ms={{ .Values.prober.iostat.thresholdSSDLatencyMS }}
        - --threshold-ssd-iops={{ .Values.prober.iostat.thresholdSSDIOPS}}
        - --threshold-ssd-total-bandwidth={{ int .Values.prober.iostat.thresholdSSDTotalBandwidth}}
        - --threshold-hdd-latency-ms={{ .Values.prober.iostat.thresholdHDDLatencyMS }}
        - --threshold-hdd-iops={{ .Values.prober.iostat.thresholdHDDIOPS }}
        - --threshold-hdd-total-bandwidth={{ int .Values.prober.iostat.thresholdHDDTotalBandwidth }}
        - --enable-prober-smart={{ .Values.prober.smart.enable }}
        - --smart-loop-interval-sec={{ .Values.prober.smart.loopIntervalSec }}
        - --enable-prober-zbs-device-health={{ .Values.prober.zbsDeviceHealth.enable }}
        - --chunk-rpc-ip={{ .Values.prober.zbsDeviceHealth.chunk.rpc.ip }}
        - --chunk-rpc-port={{ .Values.prober.zbsDeviceHealth.chunk.rpc.port }}
        - --zbs-device-health-loop-interval-sec={{ .Values.prober.zbsDeviceHealth.loopIntervalSec }}
        - --metrics-port={{ .Values.prober.metrics.port }}
        - --metrics-path={{ .Values.prober.metrics.path }}
        image: {{ .Values.global.registry }}{{ .Values.prober.image.repository }}:{{ .Values.prober.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.prober.image.pullPolicy }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            memory: {{ .Values.prober.resources.limits.memory }}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        ports:
        - name: {{ .Values.prober.metrics.portName }}
          containerPort: {{ .Values.prober.metrics.port }}  
      hostNetwork: true
