name: BuildHelmRepo

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      - 'release-*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set execute permission for build.sh
        run: chmod +x ./build.sh
      
      - name: deploy index.yaml
        env:
          BASE_URL: https://public.charts.yunna.net
        run: ./build.sh deploy_charts

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: commit to gh-pages when merging to main
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          commit_message: Automated Change
          branch: gh-pages
          commit_options: '--no-verify --signoff'
          commit_user_name: KubeSphere CI Bot
          commit_user_email: ks-ci-bot@users.noreply.github.com
          commit_author: Author KubeSphere CI Bot <ks-ci-bot@users.noreply.github.com>
          status_options: '--untracked-files=no'
