name: BuildHelmRepo

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      - 'release-*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set execute permission for build.sh
        run: chmod +x ./build.sh
      
      - name: deploy index.yaml
        env:
          BASE_URL: https://public-charts.yunna.net
        run: ./build.sh deploy_charts

      - name: Configure Git
        run: |
          git config --global user.name "KubeSphere CI Bot"
          git config --global user.email "ks-ci-bot@users.noreply.github.com"
      
      - name: Commit and Push to main
        run: |
          git add build/latest/index.yaml
          git commit -m "Update Helm index"
          git push origin main
        if: ${{ github.ref == 'refs/heads/main' }}
